manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: englmaxi
      url-base: https://github.com/englmaxi
    - name: janpfischer
      url-base: https://github.com/janpfischer
    - name: joaopedropio
      url-base: https://github.com/joaopedropio

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-dongle-display
      remote: englmaxi
      revision: v0.3
    - name: zmk-dongle-screen
      remote: janpfischer
      revision: main
    - name: snake-module
      remote: joaopedropio
      revision: master

  self:
    path: Keyboard_ZMK_config
