CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=3
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5
CONFIG_USB_DEVICE_STACK=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y
CONFIG_ZMK_KSCAN=y
CONFIG_KSCAN=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_DONGLE_SCREEN_HORIZONTAL=n
CONFIG_DONGLE_SCREEN_FLIPPED=y
# Show only split peripherals: left/right/keypad
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=n
CONFIG_DONGLE_SCREEN_DEFAULT_BRIGHTNESS=50
CONFIG_DONGLE_SCREEN_MAX_BRIGHTNESS=80
CONFIG_DONGLE_SCREEN_MIN_BRIGHTNESS=5
CONFIG_DONGLE_SCREEN_WPM_ACTIVE=n
CONFIG_DONGLE_SCREEN_MODIFIER_ACTIVE=y
