CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=3
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5
CONFIG_USB_DEVICE_STACK=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y
CONFIG_ZMK_KSCAN=y
CONFIG_KSCAN=y
CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_BACKLIGHT=n
CONFIG_DEFAULT_SCREEN="status"
CONFIG_ROTATE_DISPLAY=0
CONFIG_BATTERY_SLOTS=2
CONFIG_BATTERY_WIDGET_NUMBER=0
CONFIG_INFO_SLOT_MODE="5-slot"
CONFIG_INFO_SLOT_1="empty"
CONFIG_INFO_SLOT_2="battery"
CONFIG_INFO_SLOT_3="connectivity"
CONFIG_INFO_SLOT_4="empty"
CONFIG_INFO_SLOT_5="empty"
CONFIG_INFO_SLOT_6="theme"
CONFIG_USE_BUZZER=n
